FROM postgres:13.4-bullseye

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --fix-missing \
  && apt-get install -y --no-install-recommends \
  netcat \
  postgis \
  postgresql-13-postgis-3 \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

ARG PGSTAC_VERSION=0.4.3
RUN pip install importlib_resources requests psycopg2-binary pypgstac==${PGSTAC_VERSION} -t /asset
ENV PGSTAC_VERSION=${PGSTAC_VERSION}

COPY await-pg.sh /await-pg.sh
COPY pgstac.sh /pgstac.sh

WORKDIR /